version: "3.9"

services:
  db:
    image: postgres:15
    container_name: asf7-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asf7
    ports:
      - "5432:5432"
    volumes:
      - asf7_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: asf7-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - db
    command: npm run start:dev

volumes:
  asf7_pgdata:
